apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidmq-node
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapidmq-node
  template:
    metadata:
      labels:
        app: rapidmq-node
    spec:
      containers:
        - name: app
          image: rapidmq-node:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RABBITMQ_VHOST
              value: /rapidmq
            - name: RABBITMQ_USER
              value: app
            - name: RABBITMQ_PASS
              value: app
            - name: OTEL_SERVICE_NAME
              value: rapidmq-node
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4317
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
---
apiVersion: v1
kind: Service
metadata:
  name: rapidmq-node
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: rapidmq-node
  ports:
    - port: 8083
      targetPort: 8083
