apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidmq-python
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapidmq-python
  template:
    metadata:
      labels:
        app: rapidmq-python
    spec:
      containers:
        - name: app
          image: rapidmq-python:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RABBITMQ_VHOST
              value: /rapidmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-user-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: app-user-credentials
                  key: password
            - name: RABBITMQ_QUEUE
              value: rapidmq.queue
            - name: RABBITMQ_NODE_ROUTING_KEY
              value: rapidmq.node
            - name: OTEL_SERVICE_NAME
              value: rapidmq-python
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
---
apiVersion: v1
kind: Service
metadata:
  name: rapidmq-python
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: rapidmq-python
  ports:
    - port: 8082
      targetPort: 8082
