adminUser: admin
adminPassword: admin

auth:
  anonymous:
    enabled: true
    org_role: Admin

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        isDefault: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        isDefault: false
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir.observability.svc.cluster.local:9009/prometheus
        isDefault: true
