mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.147.0"

command:
  name: otelcol-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 200
    batch: {}
  exporters:
    otlp/tempo:
      endpoint: tempo.observability.svc.cluster.local:4317
      tls:
        insecure: true
    otlphttp/loki:
      endpoint: http://loki.observability.svc.cluster.local:3100/otlp
    prometheusremotewrite/mimir:
      endpoint: http://mimir-gateway.observability.svc.cluster.local/api/v1/push
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp/tempo]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [prometheusremotewrite/mimir]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp/loki]

service:
  type: ClusterIP

ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
