tempo:
  searchEnabled: true
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo
  microservices:
    enabled: true

service:
  type: ClusterIP
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

persistence:
  enabled: false
